package Controle;

import conexao.Conexao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicolas
 */
public class Editar_jogos extends javax.swing.JFrame {
    
    Conexao games;

    /**
     * Creates new form Editar_jogos
     */
    public Editar_jogos() {
        initComponents();
        games = new Conexao();
        games.conecta();
        games.executaSQL("select  * from tbl_games order by cod");
        preencherTabela();
        posicionarRegistro();
        tbl_games.setAutoCreateRowSorter(true);
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Close = new javax.swing.JButton();
        PrimeiroRegistro = new javax.swing.JButton();
        VoltarUmRegistro = new javax.swing.JButton();
        AvancarUmRegistro = new javax.swing.JButton();
        UltimoRegistro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_games = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        novo = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        Close.setBackground(new java.awt.Color(35, 157, 240));
        Close.setText("Voltar");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        jPanel1.add(Close);
        Close.setBounds(270, 416, 63, 25);

        PrimeiroRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_bot/resultset_first.png"))); // NOI18N
        PrimeiroRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimeiroRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(PrimeiroRegistro);
        PrimeiroRegistro.setBounds(30, 216, 49, 25);

        VoltarUmRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_bot/resultset_previous.png"))); // NOI18N
        VoltarUmRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarUmRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(VoltarUmRegistro);
        VoltarUmRegistro.setBounds(90, 216, 49, 25);

        AvancarUmRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_bot/resultset_next.png"))); // NOI18N
        AvancarUmRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvancarUmRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(AvancarUmRegistro);
        AvancarUmRegistro.setBounds(150, 216, 49, 25);

        UltimoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_bot/resultset_last.png"))); // NOI18N
        UltimoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltimoRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(UltimoRegistro);
        UltimoRegistro.setBounds(210, 216, 49, 25);

        tbl_games.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome", "Preço "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_games);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 260, 452, 91);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Preço:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 130, 60, 17);
        jPanel1.add(txtCod);
        txtCod.setBounds(125, 50, 160, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Código:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 50, 60, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nome:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 88, 60, 17);
        jPanel1.add(txtNome);
        txtNome.setBounds(125, 88, 160, 22);
        jPanel1.add(txtPreco);
        txtPreco.setBounds(125, 126, 160, 22);

        novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_bot/add.png"))); // NOI18N
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });
        jPanel1.add(novo);
        novo.setBounds(330, 220, 49, 23);

        salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_bot/disk.png"))); // NOI18N
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        jPanel1.add(salvar);
        salvar.setBounds(390, 220, 49, 25);

        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_bot/application_edit.png"))); // NOI18N
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        jPanel1.add(editar);
        editar.setBounds(450, 220, 49, 25);

        excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_bot/application_delete.png"))); // NOI18N
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        jPanel1.add(excluir);
        excluir.setBounds(510, 220, 49, 25);

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });
        jPanel1.add(txtPesquisa);
        txtPesquisa.setBounds(450, 100, 120, 22);

        jLabel2.setText("Pesquisa por nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 100, 110, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_CloseActionPerformed

    private void PrimeiroRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimeiroRegistroActionPerformed
        // TODO add your handling code here:
        try {
            games.resultset.first();
            mostrar_Dados();
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Nã foi possível acessar o primeiro registro: " +erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_PrimeiroRegistroActionPerformed

    private void VoltarUmRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarUmRegistroActionPerformed
        // TODO add your handling code here:
        try {
            games.resultset.previous();
            mostrar_Dados();
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no registro anterior: " +erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_VoltarUmRegistroActionPerformed

    private void AvancarUmRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvancarUmRegistroActionPerformed
        // TODO add your handling code here:
        try {
            games.resultset.next();
            mostrar_Dados();
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no próximo registro: " +erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_AvancarUmRegistroActionPerformed

    private void UltimoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimoRegistroActionPerformed
        // TODO add your handling code here:
        try {
            games.resultset.last();
            mostrar_Dados();
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no último registro: " +erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_UltimoRegistroActionPerformed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        // TODO add your handling code here:
        txtCod.setText("");
        txtNome.setText("");
        txtPreco.setText("");
        txtCod.requestFocus();
    }//GEN-LAST:event_novoActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
        String nome = txtNome.getText();
        String Preco = txtPreco.getText();
        
        
        try{
            String insert_sql="insert into tbl_games (nome, preco) values ('" + nome + "','" + Preco + "')";
            games.statement.executeUpdate(insert_sql);
            JOptionPane.showMessageDialog(null, "\n Gravação realizada com sucesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            games.executaSQL("select * from tbl_games order by cod");
            games.resultset.first();
            preencherTabela();
            mostrar_Dados();
        }catch(SQLException errosql){
            JOptionPane.showMessageDialog(null, "\n Erro na gravação: \n " + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
        
        tbl_games.addRowSelectionInterval(tbl_games.getRowCount()-1,tbl_games.getRowCount() -1);
    }//GEN-LAST:event_salvarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
        String nome = txtNome.getText();
        String Preco = txtPreco.getText();
        String sql = "";
        String msg = "";
        int LinhaSelecionada = tbl_games.getSelectedRow();
        
        try{
            if(txtCod.getText().equals("")){
                sql= "insert into tbl_games (nome, preco) values ('"+ nome +"', '"+ Preco +"')";
                msg = "Gravação de um novo registro";
            }else{
                sql = "update tbl_games set nome='" + nome +"', preco='" + Preco + "' where cod = " + txtCod.getText();
                msg = "Alteração de registro";
            }
            games.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, msg + "realizada com sucesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            
            games.executaSQL("select * from tbl_games order by cod");
            games.resultset.first();
            
            preencherTabela();
            mostrar_Dados();
            
             tbl_games.addRowSelectionInterval(LinhaSelecionada, LinhaSelecionada); // selecionar primeira linha
        }catch(SQLException errosql){
            JOptionPane.showMessageDialog(null, "\n Erro na gravação: \n" + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_editarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        String sql= "";
        int LinhaSelecionada = tbl_games.getSelectedRow();// pega linha selecionada
        try{
            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro: ", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);
            if (resposta == 0){
                sql = "delete from tbl_games where cod =" +txtCod.getText();
                int excluir = games.statement.executeUpdate(sql);
            if(excluir==1){
                JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                games.executaSQL("select * from tbl_games order by cod");
                games.resultset.first();
                preencherTabela();
                posicionarRegistro();
                tbl_games.addRowSelectionInterval(tbl_games.getRowCount()-1, tbl_games.getRowCount()-1); // selecionar primeira linha
            }else{
               JOptionPane.showMessageDialog(null, "Operação cancelada pelo usuário!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
            }
            }      
        }catch(SQLException excecao){
            JOptionPane.showMessageDialog(null, "Erro na exclusão: " +excecao, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        // TODO add your handling code here:
        try {
            String pesquisa = "select * from tbl_games where nome like '" + txtPesquisa.getText() + "%'";
            games.executaSQL(pesquisa);
            
            if(games.resultset.first()){
                preencherTabela();
            }
            else{
                
            }
        }catch (SQLException errosql){
            JOptionPane.showMessageDialog(null, "\n Os dados digitados não foram localizados!! :\n " + errosql, "Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtPesquisaKeyReleased

    public void preencherTabela(){
        tbl_games.getColumnModel().getColumn(0).setPreferredWidth(4);
        tbl_games.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbl_games.getColumnModel().getColumn(2).setPreferredWidth(11);
       
        
        DefaultTableModel modelo = (DefaultTableModel) tbl_games.getModel();
        modelo.setNumRows(0);
        
        try{
            games.resultset.beforeFirst();
            while(games.resultset.next()){
                modelo.addRow(new Object[]{
                    games.resultset.getString("cod"),games.resultset.getString("nome"),games.resultset.getString("preco")
            });
            }
        }catch(SQLException erro) {
            JOptionPane.showMessageDialog(null,"\n Erro ao listar dados da tabela!! :\n "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }
    
    public void posicionarRegistro() {
        try {
            games.resultset.first();
            mostrar_Dados();
            }catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possível posicionar no primeiro registro: "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
            }
    }
    
    public void mostrar_Dados(){
        try {
            txtCod.setText(games.resultset.getString("cod"));
            txtNome.setText(games.resultset.getString("nome"));
            txtPreco.setText(games.resultset.getString("preco"));
        }catch(SQLException erro){
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar_jogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar_jogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar_jogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar_jogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar_jogos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AvancarUmRegistro;
    private javax.swing.JButton Close;
    private javax.swing.JButton PrimeiroRegistro;
    private javax.swing.JButton UltimoRegistro;
    private javax.swing.JButton VoltarUmRegistro;
    private javax.swing.JButton editar;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novo;
    private javax.swing.JButton salvar;
    private javax.swing.JTable tbl_games;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
